import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#fcf9f8",
        "on-primary-fixed": "#1c1c1a",
        "error-container": "#ffdad6",
        "surface-bright": "#fcf9f8",
        "surface-variant": "#e4e2e1",
        "surface-tint": "#5f5e5b",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#474744",
        "secondary-fixed-dim": "#d5c3be",
        "on-surface-variant": "#464741",
        "on-secondary-container": "#6f615d",
        "inverse-surface": "#303030",
        "on-tertiary-fixed": "#241a00",
        "secondary-container": "#f2ded9",
        "on-background": "#1b1c1c",
        "inverse-primary": "#c8c6c2",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1b1c1c",
        "on-primary-container": "#72706d",
        "tertiary-container": "#fff5e3",
        "surface-container-high": "#eae7e7",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#e9c349",
        "primary-fixed-dim": "#c8c6c2",
        "on-tertiary-fixed-variant": "#574500",
        "on-secondary-fixed": "#231916",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-container": "#896d00",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e4e2e1",
        tertiary: "#735c00",
        "primary-fixed": "#e5e2de",
        "on-secondary-fixed-variant": "#514440",
        outline: "#777771",
        "tertiary-fixed": "#ffe088",
        "secondary-fixed": "#f2ded9",
        "surface-container": "#f0eded",
        surface: "#fcf9f8",
        "primary-container": "#f9f6f2",
        primary: "#5f5e5b",
        secondary: "#695b58",
        "surface-dim": "#dcd9d9",
        "outline-variant": "#c7c7bf",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f3f0f0",
      },
      spacing: {
        "margin-mobile": "16px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        gutter: "24px",
        unit: "8px",
      },
      fontFamily: {
        "label-md": ["var(--font-plus-jakarta)"],
        "headline-sm": ["var(--font-bodoni)"],
        "display-lg-mobile": ["var(--font-bodoni)"],
        "body-md": ["var(--font-plus-jakarta)"],
        "body-lg": ["var(--font-plus-jakarta)"],
        "headline-md": ["var(--font-bodoni)"],
        "display-lg": ["var(--font-bodoni)"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
